module.exports = (sequeluze, DataTypes) =>{
    return sequeluze.define('post',{
        title:{
            type:DataTypes.STRING(40),
            allowNull:false,
        },
        imageURL:{
            type:DataTypes.STRING(100),
            allowNull:true
        },
        description:{
            type:DataTypes.STRING(1000),
            allowNull:false,
        },
        nick:{
            type:DataTypes.STRING(20),
            allowNull:false,
        },
        visited:{
            type:DataTypes.INTEGER.UNSIGNED,
            defaultValue:0
        },
        type:{
            type:DataTypes.STRING(10),
            allowNull:false,
            defaultValue:'normal'
        },
        recommend:{
            type:DataTypes.INTEGER.UNSIGNED,
            defaultValue:0
        },
        boardName:{
            type:DataTypes.INTEGER.UNSIGNED,
            allowNull:false,
        }
    },{
        timestamps:true,
        paranoid:true
    })
}